name = "TeaFiles"
uuid = "c40ccc24-2f2a-4785-85cd-06e8176bc8e2"
authors = ["Thomas Gillam <tpgillam@googlemail.com> and contributors"]
version = "0.1.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
AutoHashEquals = "0.2"
Bijections = "0.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
